import { z } from 'zod';
import type { ActionTarget, Agent, SimulationWorld } from '../domain/types';
export const providerIds=['local-rules','ollama','openai'] as const;
export type ProviderId=(typeof providerIds)[number];
export const actionNames=['Drink','Eat','Sleep','TalkTo','Observe'] as const;
export const DecisionSchema=z.object({goal:z.string().min(1).max(140),action:z.enum(actionNames),targetId:z.string().min(1),intent:z.string().min(1).max(220),utterance:z.string().max(180).optional()});
export type DecisionResponse=z.infer<typeof DecisionSchema>;
export type Candidate={id:string;action:DecisionResponse['action'];target:ActionTarget;label:string};
export type MindContext={agentId:string;identity:{name:string;age:number;traits:string[];preferences:string[]};time:string;needs:Agent['needs'];currentGoal:string;recentMemories:string[];relationships:{name:string;label:string;affinity:number}[];candidates:Candidate[]};
export type ProviderStatus={id:ProviderId;available:boolean;label:string;detail?:string};
export function candidatesFor(agent:Agent,world:SimulationWorld):Candidate[]{const items:Candidate[]=[];for(const fact of agent.knowledge){const object=world.objects.find(o=>o.id===fact.id);if(object?.type==='well')items.push({id:`drink:${object.id}`,action:'Drink',target:{kind:'object',objectId:object.id},label:`Drink at ${object.name}`});if(object?.type==='berryBush'&&object.stock)items.push({id:`eat:${object.id}`,action:'Eat',target:{kind:'object',objectId:object.id},label:`Eat from ${object.name}`});if(object?.type==='bed')items.push({id:`sleep:${object.id}`,action:'Sleep',target:{kind:'object',objectId:object.id},label:`Rest at ${object.name}`});if(fact.kind==='agent')items.push({id:`talk:${fact.id}`,action:'TalkTo',target:{kind:'agent',agentId:fact.id},label:`Talk to ${fact.name}`});}for(const p of [{x:35,y:25,label:'the northern meadow'},{x:50,y:82,label:'the southern path'},{x:44,y:55,label:'the common clearing'}])items.push({id:`observe:${p.x}:${p.y}`,action:'Observe',target:{kind:'position',position:{x:p.x,y:p.y}},label:`Observe ${p.label}`});return items;}
export function contextFor(agent:Agent,world:SimulationWorld):MindContext{const lookup=(id:string)=>world.agents.find(a=>a.id===id)?.name??'Neighbor';return{agentId:agent.id,identity:{name:agent.name,age:agent.age,traits:agent.traits,preferences:agent.preferences},time:`Day ${world.day}, ${String(Math.floor(world.minute/60)).padStart(2,'0')}:${String(world.minute%60).padStart(2,'0')}`,needs:agent.needs,currentGoal:agent.currentGoal,recentMemories:agent.recentMemories.slice(0,3).map(m=>m.description),relationships:agent.relationships.map(r=>({name:lookup(r.agentId),label:r.label,affinity:r.affinity})),candidates:candidatesFor(agent,world)};}
export function normalizeDecision(response:DecisionResponse,context:MindContext):{goal:string;target:ActionTarget;action:DecisionResponse['action'];intent:string;utterance?:string}|null{const candidate=context.candidates.find(c=>c.id===response.targetId&&c.action===response.action);return candidate?{goal:response.goal,target:candidate.target,action:response.action,intent:response.intent,utterance:response.utterance}:null;}
