import { describe, expect, it } from 'vitest';
import { createWorld } from '../domain/world';
import { validateAndApply } from './actions';
import { tickWorld } from './engine';
import { findPath, isBlocked } from './navigation';
const run=(world:ReturnType<typeof createWorld>,ticks=160)=>{let next=world;for(let i=0;i<ticks;i++)next=tickWorld(next);return next;}; const resident=(world:ReturnType<typeof createWorld>,id:string)=>world.agents.find(a=>a.id===id)!;
describe('situated authoritative simulation',()=>{
  it('a thirsty resident walks to the well, drinks, remembers it, and does not remain walking',()=>{const w=createWorld(),m=resident(w,'a-mara');m.needs.thirst=5;const after=run(w,100),mara=resident(after,'a-mara');expect(mara.needs.thirst).toBeGreaterThan(35);expect(after.events.some(e=>e.description.includes('cool water'))).toBe(true);expect(mara.currentAction.kind==='WalkTo'&&mara.currentAction.waypoint===mara.currentAction.path?.length).toBe(false);});
  it('a hungry resident reaches known berries and eats through simulation ticks',()=>{const w=createWorld(),e=resident(w,'a-elena');e.needs.hunger=4;const after=run(w,110);expect(resident(after,'a-elena').needs.hunger).toBeGreaterThan(30);expect(after.objects.find(o=>o.id==='berries')!.stock).toBeLessThan(18);expect(after.events.some(x=>x.description.includes('sunberries'))).toBe(true);});
  it('a tired resident navigates home and sleeps',()=>{const w=createWorld(),j=resident(w,'a-jonah');j.needs.energy=4;const after=run(w,120);expect(resident(after,'a-jonah').needs.energy).toBeGreaterThan(30);expect(after.events.some(x=>x.description.includes('rested peacefully'))).toBe(true);});
  it('a failed interaction cannot mutate state',()=>{const w=createWorld(),m=resident(w,'a-mara'),before=m.needs.thirst;const result=validateAndApply(m,{kind:'Drink',target:{kind:'object',objectId:'well'},progress:2,duration:2,state:'running'},w);expect(result.ok).toBe(false);expect(m.needs.thirst).toBe(before);});
  it('paths cross the river only through the bridge gap and avoid cabin terrain',()=>{const w=createWorld(),path=findPath({x:78,y:47},{x:42,y:48},w);expect(path.some(p=>p.x>=61&&p.x<=72&&p.y>=47&&p.y<=55)).toBe(true);expect(path.every(p=>!isBlocked({x:Math.floor(p.x/4),y:Math.floor(p.y/4)}))).toBe(true);});
  it('perception discovers local knowledge and a nearby social interaction completes for both agents',()=>{let w=createWorld();const m=resident(w,'a-mara'),j=resident(w,'a-jonah');m.position={x:50,y:50};j.position={x:53,y:50};m.needs.social=2;j.needs.social=2;const provider={decide:({agent}: {agent: typeof m})=>agent.id==='a-mara'?{goal:'Talk with Jonah',target:{kind:'agent' as const,agentId:'a-jonah'},action:'TalkTo' as const}:null};for(let i=0;i<18;i++)w=tickWorld(w,provider);expect(resident(w,'a-mara').knowledge.some(k=>k.id==='a-jonah')).toBe(true);expect(w.events.some(e=>e.description.includes('warm conversation'))).toBe(true);expect(resident(w,'a-mara').needs.social).toBeGreaterThan(10);expect(resident(w,'a-jonah').needs.social).toBeGreaterThan(10);});
  it('continues autonomously after discovery rather than becoming stuck',()=>{const before=createWorld(),known=before.agents.map(a=>a.knowledge.length),after=run(before,360);expect(after.events.length).toBeGreaterThan(8);expect(after.agents.some((a,i)=>a.knowledge.length>known[i])).toBe(true);expect(after.agents.every(a=>a.position.x>1&&a.position.x<99&&a.position.y>1&&a.position.y<99)).toBe(true);});
  it('remains deterministic with identical seed and inputs',()=>{expect(run(createWorld(),120)).toEqual(run(createWorld(),120));});
});
