import type { Agent, Memory, PlanStep, SimulationWorld } from '../domain/types';
import { actAction, targetPosition, validateAndApply, walkAction } from './actions';
import { LocalCognition, type CognitionProvider, type Decision } from './cognition';
import { findPath } from './navigation';
import { learn, perceive } from './perception';
const cognition=new LocalCognition(),clamp=(n:number)=>Math.max(0,Math.min(100,n));
function remember(agent:Agent,world:SimulationWorld,type:string,description:string,importance=.45,participants=[agent.id]){const m:Memory={id:`m-${world.tick}-${agent.id}-${world.events.length}`,timestamp:world.day*1440+world.minute,type,participants,place:'Willowmere',description,importance,confidence:1};agent.recentMemories=[m,...agent.recentMemories].slice(0,5);if(importance>.6)agent.longTermMemories.push(m);world.events=[{...m,agentName:agent.name},...world.events].slice(0,40);}
function decay(a:Agent){a.needs.hunger=clamp(a.needs.hunger-.18);a.needs.thirst=clamp(a.needs.thirst-.28);a.needs.energy=clamp(a.needs.energy-.12);a.needs.social=clamp(a.needs.social-.06);a.needs.comfort=clamp(a.needs.comfort-.04);}
function planFor(d:Decision):PlanStep[]{return d.target.kind==='position'?[{kind:'WalkTo',target:d.target},{kind:'Observe',target:d.target}]:[{kind:'WalkTo',target:d.target},{kind:d.action,target:d.target}];}
function startNext(agent:Agent,world:SimulationWorld,provider:CognitionProvider){if(!agent.plan.length){const d=provider.decide({agent,perception:agent.perception,knowledge:agent.knowledge,tick:world.tick,seed:world.seed});if(!d){agent.currentAction={kind:'Idle',progress:0,duration:3,state:'running'};agent.currentGoal='Look for something useful';return;}agent.currentGoal=d.goal;agent.plan=planFor(d);}const step=agent.plan[0],end=targetPosition(step.target,world);if(!end){agent.plan=[];agent.currentAction={kind:'Idle',progress:0,duration:1,state:'failed'};return;}agent.currentAction=step.kind==='WalkTo'?walkAction(end,findPath(agent.position,end,world)):actAction(step.kind,step.target);}
function complete(agent:Agent,world:SimulationWorld,provider:CognitionProvider){agent.plan.shift();startNext(agent,world,provider);}
function advance(agent:Agent,world:SimulationWorld,provider:CognitionProvider){const action=agent.currentAction;if(action.kind==='WalkTo'&&action.path){const index=action.waypoint??0,point=action.path[index],dx=point.x-agent.position.x,dy=point.y-agent.position.y,d=Math.hypot(dx,dy),speed=1.35;if(d<=speed){agent.position={...point};action.waypoint=index+1;if(index+1>=action.path.length){action.state='success';complete(agent,world,provider);}return;}agent.position={x:agent.position.x+dx/d*speed,y:agent.position.y+dy/d*speed};agent.facing=dx<0?'left':'right';return;}action.progress++;if(action.progress<action.duration)return;if(action.kind!=='Idle'){const r=validateAndApply(agent,action,world);remember(agent,world,r.ok?'action':'failure',r.message,r.ok?.7:.3);if(r.ok&&r.other)remember(r.other,world,'conversation',r.message,.7,[agent.id,r.other.id]);}complete(agent,world,provider);}
export function tickWorld(world:SimulationWorld,provider:CognitionProvider=cognition):SimulationWorld{const next=structuredClone(world) as SimulationWorld;next.tick++;next.minute+=2;if(next.minute>=1440){next.day++;next.minute-=1440;}next.agents.forEach(a=>{a.perception=perceive(a,next);learn(a,next);decay(a);advance(a,next,provider);});return next;}
export const formatTime=(world:SimulationWorld)=>`Day ${world.day} · ${String(Math.floor(world.minute/60)).padStart(2,'0')}:${String(world.minute%60).padStart(2,'0')}`;
