import 'dotenv/config';
import express from 'express';
import { createServer as createViteServer } from 'vite';
import { DecisionSchema, MindContextSchema, providerIds } from './src/cognition/contracts';
import { z } from 'zod';
import { ollamaDecision, ollamaModels, openAiDecision, providerStatus } from './server/cognition';
const app=express();app.use(express.json({limit:'64kb'}));
app.get('/api/cognition/providers',async(_req,res)=>{res.json({providers:await providerStatus(),defaults:{provider:process.env.COGNITION_PROVIDER??'local-rules',ollamaModel:process.env.OLLAMA_MODEL??'',openaiModel:process.env.OPENAI_MODEL??''},limits:{ollamaMaxConcurrent:Math.max(1,Number(process.env.OLLAMA_MAX_CONCURRENT??1)),ollamaMinRealSecondsBetweenCalls:Math.max(0,Number(process.env.OLLAMA_MIN_REAL_SECONDS_BETWEEN_CALLS??5))}});});
app.get('/api/cognition/ollama/models',async(_req,res)=>{try{res.json({models:await ollamaModels()});}catch(error){res.status(503).json({error:error instanceof Error?error.message:'Ollama offline'});}});
const RequestSchema=z.object({provider:z.enum(providerIds),model:z.string().max(160),context:MindContextSchema});
app.post('/api/cognition/decision',async(req,res)=>{const parsed=RequestSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Invalid cognition request'});const{provider,model,context}=parsed.data;if(provider!=='local-rules'&&!model)return res.status(400).json({error:'A provider model is required'});try{if(provider==='local-rules')return res.status(400).json({error:'Local Rules is in-browser deterministic cognition'});const decision=provider==='ollama'?await ollamaDecision(context,model):await openAiDecision(context,model);res.json({decision:DecisionSchema.parse(decision)});}catch(error){res.status(502).json({error:error instanceof Error?error.message:'Cognition request failed'});}});
const vite=await createViteServer({server:{middlewareMode:true},appType:'spa'});app.use(vite.middlewares);const port=Number(process.env.PORT??5173);app.listen(port,()=>console.log(`Willowmere running at http://127.0.0.1:${port}`));
