import 'dotenv/config';
import express from 'express';
import { createServer as createViteServer } from 'vite';
import { DecisionSchema, type MindContext, providerIds } from './src/cognition/contracts';
import { ollamaDecision, ollamaModels, openAiDecision, providerStatus } from './server/cognition';
const app=express();app.use(express.json({limit:'64kb'}));
app.get('/api/cognition/providers',async(_req,res)=>{res.json({providers:await providerStatus(),defaultProvider:process.env.COGNITION_PROVIDER??'local-rules'});});
app.get('/api/cognition/ollama/models',async(_req,res)=>{try{res.json({models:await ollamaModels()});}catch(error){res.status(503).json({error:error instanceof Error?error.message:'Ollama offline'});}});
app.post('/api/cognition/decision',async(req,res)=>{const provider=String(req.body?.provider??'local-rules');const model=String(req.body?.model??'');const context=req.body?.context as MindContext;if(!providerIds.includes(provider as typeof providerIds[number])||!context?.agentId)return res.status(400).json({error:'Invalid cognition request'});try{if(provider==='local-rules')return res.status(400).json({error:'Local Rules is in-browser deterministic cognition'});const decision=provider==='ollama'?await ollamaDecision(context,model):await openAiDecision(context,model);res.json({decision:DecisionSchema.parse(decision)});}catch(error){res.status(502).json({error:error instanceof Error?error.message:'Cognition request failed'});}});
const vite=await createViteServer({server:{middlewareMode:true},appType:'spa'});app.use(vite.middlewares);const port=Number(process.env.PORT??5173);app.listen(port,()=>console.log(`Willowmere running at http://127.0.0.1:${port}`));
