import { lazy, Suspense, useEffect, useMemo, useRef, useState } from 'react';
import { createWorld } from '../domain/world';
import type { Agent, NeedName, SimulationWorld } from '../domain/types';
import { applyExternalDecision, formatTime, tickWorld } from '../simulation/engine';
import { EmergencyReflexProvider } from '../cognition/reflex';
import type { ProviderId, ProviderStatus } from '../cognition/contracts';
import { CognitionCoordinator } from '../runtime/cognitionCoordinator';
import { clearWorld, loadMindPreference, loadWorld, saveMindPreference, saveWorld } from '../runtime/persistence';
const WillowmereCanvas=lazy(()=>import('../rendering/WorldScene').then(module=>({default:module.WillowmereCanvas})));
const needs:NeedName[]=['hunger','thirst','energy','social','comfort'];const reflex=new EmergencyReflexProvider();
function NeedBar({label,value}:{label:string;value:number}){return <div className="need"><span>{label}</span><div><i style={{width:`${value}%`}}/></div><b>{Math.round(value)}</b></div>}
function Inspector({agent,world,close,mindStatus,intent}:{agent:Agent;world:SimulationWorld;close:()=>void;mindStatus:string;intent?:string}){const lookup=(id:string)=>world.agents.find(a=>a.id===id);return <aside className="inspector"><button className="close" onClick={close}>x</button><div className="profile"><span className="portrait" style={{background:agent.shirt}}><i style={{background:agent.color}}/></span><div><h2>{agent.name}</h2><p>{agent.age} years · {agent.traits.join(' · ')}</p></div></div><section><label>MIND</label><strong>{mindStatus}</strong>{intent&&<p className="goal">{intent}</p>}</section><section><label>NOW</label><strong>{agent.currentAction.kind==='WalkTo'?'Walking the planned route':agent.currentAction.kind}</strong><p className="goal">Goal: {agent.currentGoal}</p></section><section><label>WELLBEING</label>{needs.map(n=><NeedBar key={n} label={n} value={agent.needs[n]}/>)}</section><section><label>KNOWN WORLD</label>{agent.knowledge.slice(0,5).map(k=><p className="memory" key={k.id}>{k.kind==='agent'?'Met ':''}{k.name}</p>)}</section><section><label>RECENTLY</label>{agent.recentMemories.slice(0,3).map(m=><p className="memory" key={m.id}>{m.description}</p>)}</section><section><label>CONNECTIONS</label>{agent.relationships.map(r=><p className="relation" key={r.agentId}><b>{lookup(r.agentId)?.name}</b><span>{r.label} · {Math.round(r.affinity*100)}%</span></p>)}</section></aside>}
export function App(){const saved=loadMindPreference();const[world,setWorld]=useState<SimulationWorld>(()=>loadWorld()??createWorld());const[speed,setSpeed]=useState(1);const[selected,setSelected]=useState('a-mara');const[debug,setDebug]=useState(false);const[provider,setProvider]=useState<ProviderId>((saved?.provider as ProviderId)??'local-rules');const[model,setModel]=useState(saved?.model??'');const[providers,setProviders]=useState<ProviderStatus[]>([]);const[models,setModels]=useState<{name:string}[]>([]);const[refresh,setRefresh]=useState(0);const coordinator=useRef(new CognitionCoordinator());const worldRef=useRef(world);const[intents,setIntents]=useState<Record<string,string>>({});worldRef.current=world;
  useEffect(()=>{fetch('/api/cognition/providers').then(r=>r.json()).then(x=>setProviders(x.providers??[])).catch(()=>setProviders([{id:'local-rules',available:true,label:'Local Rules'},{id:'ollama',available:false,label:'Ollama',detail:'OFFLINE'},{id:'openai',available:false,label:'OpenAI'}]));fetch('/api/cognition/ollama/models').then(r=>r.ok?r.json():{models:[]}).then(x=>setModels(x.models??[])).catch(()=>setModels([]));},[refresh]);
  useEffect(()=>saveMindPreference({provider,model}),[provider,model]);useEffect(()=>{const id=setInterval(()=>saveWorld(worldRef.current),30000);return()=>clearInterval(id);},[]);
  useEffect(()=>{if(!speed)return;const id=setInterval(()=>setWorld(previous=>tickWorld(previous,provider==='local-rules'?undefined:reflex)),Math.max(90,700/speed));return()=>clearInterval(id);},[speed,provider]);
  useEffect(()=>{coordinator.current.schedule(world,{provider,model},(agentId,decision)=>{if(!decision)return;setIntents(previous=>({...previous,[agentId]:decision.intent}));setWorld(current=>applyExternalDecision(current,agentId,decision));});},[world,provider,model]);
  const agent=world.agents.find(a=>a.id===selected);const mood=useMemo(()=>{const h=world.minute/60;return h<6||h>20?'Moonlit quiet':h<8?'Morning mist':h>17?'Amber evening':'Golden meadow';},[world.minute]);const metrics=coordinator.current.metrics();const save=()=>saveWorld(world);const reset=()=>{if(window.confirm('Create a new Willowmere world? Your autosave will be replaced.')){clearWorld();setWorld(createWorld());setIntents({});}};const providerLabel=providers.find(p=>p.id===provider)?.label??provider;
  return <main className="app three-app"><header><div className="brand"><span>*</span><div><h1>Willowmere</h1><p>an autonomous little world</p></div></div><div className="time"><b>{formatTime(world)}</b><span>{mood}</span></div><div className="mind-control"><label>MIND</label><select value={provider} onChange={e=>setProvider(e.target.value as ProviderId)}><option value="local-rules">Local Rules</option><option value="ollama" disabled={!providers.find(p=>p.id==='ollama')?.available}>Ollama {providers.find(p=>p.id==='ollama')?.available?'':'(offline)'}</option><option value="openai" disabled={!providers.find(p=>p.id==='openai')?.available}>OpenAI</option></select>{provider==='ollama'&&<select value={model} onChange={e=>setModel(e.target.value)}><option value="">Select model</option>{models.map(m=><option key={m.name} value={m.name}>{m.name}</option>)}</select>}<button onClick={()=>setRefresh(x=>x+1)}>↻</button></div><div className="controls"><button className={speed===0?'active':''} onClick={()=>setSpeed(0)}>II</button><button className={speed===1?'active':''} onClick={()=>setSpeed(1)}>1x</button><button className={speed===3?'active':''} onClick={()=>setSpeed(3)}>3x</button><button onClick={save}>SAVE</button><button onClick={reset}>NEW</button><button className={debug?'active':''} onClick={()=>setDebug(!debug)}>DEV</button></div></header><div className="scene-wrap"><Suspense fallback={<div className="scene-loading">Growing Willowmere...</div>}><WillowmereCanvas world={world} selectedId={selected} onSelect={setSelected} debug={debug}/></Suspense><div className="legend"><span><i className="dot"/> {providerLabel} · click a resident</span><span>drag to pan · scroll to zoom</span></div>{debug&&<div className="debug"><b>DEVELOPER VIEW</b><p>{providerLabel} · {models.length} local models</p><p>queue {metrics.queue} · running {metrics.running} · avg {metrics.averageLatencyMs}ms</p><p>completed {metrics.completed} · rejected {metrics.rejected} · fallback {metrics.fallbacks}</p><p>{metrics.lastError&&`last error: ${metrics.lastError}`}</p></div>}</div><div className="bottom"><div><b>Settlement pulse</b><span>{world.agents.filter(a=>a.currentAction.kind==='WalkTo').length} residents en route · terrain-aware navigation</span></div><div className="event"><b>Latest</b><span>{world.events[0]?.description??'The residents are beginning their day.'}</span></div></div>{agent&&<Inspector agent={agent} world={world} close={()=>setSelected('')} mindStatus={provider==='local-rules'?'LOCAL':coordinator.current.status(agent.id)} intent={intents[agent.id]}/>}</main>}
