import { useEffect, useMemo, useState } from 'react';
import { createWorld } from '../domain/world';
import type { Agent, NeedName, SimulationWorld } from '../domain/types';
import { formatTime, tickWorld } from '../simulation/engine';
import { WillowmereCanvas } from '../rendering/WorldScene';
const needs:NeedName[]=['hunger','thirst','energy','social','comfort'];
function NeedBar({label,value}:{label:string;value:number}){return <div className="need"><span>{label}</span><div><i style={{width:`${value}%`}}/></div><b>{Math.round(value)}</b></div>}
function Inspector({agent,world,close}:{agent:Agent;world:SimulationWorld;close:()=>void}){const lookup=(id:string)=>world.agents.find(a=>a.id===id);return <aside className="inspector"><button className="close" onClick={close}>x</button><div className="profile"><span className="portrait" style={{background:agent.shirt}}><i style={{background:agent.color}}/></span><div><h2>{agent.name}</h2><p>{agent.age} years · {agent.traits.join(' · ')}</p></div></div><section><label>NOW</label><strong>{agent.currentAction.kind==='WalkTo'?'Walking the planned route':agent.currentAction.kind}</strong><p className="goal">Goal: {agent.currentGoal}</p></section><section><label>WELLBEING</label>{needs.map(n=><NeedBar key={n} label={n} value={agent.needs[n]}/>)}</section><section><label>KNOWN WORLD</label>{agent.knowledge.slice(0,5).map(k=><p className="memory" key={k.id}>{k.kind==='agent'?'Met ':''}{k.name}</p>)}</section><section><label>RECENTLY</label>{agent.recentMemories.slice(0,3).map(m=><p className="memory" key={m.id}>{m.description}</p>)}</section><section><label>CONNECTIONS</label>{agent.relationships.map(r=><p className="relation" key={r.agentId}><b>{lookup(r.agentId)?.name}</b><span>{r.label} · {Math.round(r.affinity*100)}%</span></p>)}</section></aside>}
export function App(){const[world,setWorld]=useState(createWorld);const[speed,setSpeed]=useState(1);const[selected,setSelected]=useState('a-mara');const[debug,setDebug]=useState(false);useEffect(()=>{if(!speed)return;const id=setInterval(()=>setWorld(tickWorld),Math.max(90,700/speed));return()=>clearInterval(id);},[speed]);const agent=world.agents.find(a=>a.id===selected);const mood=useMemo(()=>{const h=world.minute/60;return h<6||h>20?'Moonlit quiet':h<8?'Morning mist':h>17?'Amber evening':'Golden meadow';},[world.minute]);return <main className="app three-app"><header><div className="brand"><span>*</span><div><h1>Willowmere</h1><p>an autonomous little world</p></div></div><div className="time"><b>{formatTime(world)}</b><span>{mood}</span></div><div className="controls"><button className={speed===0?'active':''} onClick={()=>setSpeed(0)}>II</button><button className={speed===1?'active':''} onClick={()=>setSpeed(1)}>1x</button><button className={speed===3?'active':''} onClick={()=>setSpeed(3)}>3x</button><button className={debug?'active':''} onClick={()=>setDebug(!debug)}>DEV</button></div></header><div className="scene-wrap"><WillowmereCanvas world={world} selectedId={selected} onSelect={setSelected} debug={debug}/><div className="legend"><span><i className="dot"/> click a resident to observe</span><span>drag to pan · scroll to zoom</span></div>{debug&&<div className="debug"><b>DEVELOPER VIEW</b><p>tick {world.tick} · seed {world.seed}</p><p>plan: {agent?.plan.map(s=>s.kind).join(' -> ')||'none'}</p><p>perception: {agent?.perception.objects.length||0} objects, {agent?.perception.agents.length||0} people</p><p>{world.events.length} events · berry stock {world.objects.find(o=>o.id==='berries')?.stock}</p></div>}</div><div className="bottom"><div><b>Settlement pulse</b><span>{world.agents.filter(a=>a.currentAction.kind==='WalkTo').length} residents en route · terrain-aware navigation</span></div><div className="event"><b>Latest</b><span>{world.events[0]?.description??'The residents are beginning their day.'}</span></div></div>{agent&&<Inspector agent={agent} world={world} close={()=>setSelected('')}/>}</main>}
