import { useEffect, useMemo, useState } from 'react';
import { createWorld } from '../domain/world';
import type { Agent, NeedName, SimulationWorld, WorldObject } from '../domain/types';
import { formatTime, tickWorld } from '../simulation/engine';
const needs: NeedName[]=['hunger','thirst','energy','social','comfort'];
function Person({ agent, selected, onSelect }: {agent:Agent;selected:boolean;onSelect:()=>void}) { return <button className={`person ${selected?'selected':''}`} onClick={onSelect} style={{left:`${agent.position.x}%`,top:`${agent.position.y}%`}} aria-label={`Select ${agent.name}`}><span className="nameplate">{agent.name.split(' ')[0]}</span><i className="hair" style={{background:agent.color}}/><i className="head"/><i className="body" style={{background:agent.shirt}}/><i className="legs"/></button>; }
function ObjectView({ object }: {object:WorldObject}) { const style={left:`${object.position.x}%`,top:`${object.position.y}%`}; if(object.type==='tree')return <span className="tree" style={style}><b/><i/></span>; if(object.type==='cabin')return <span className="cabin" style={style}><b/><i/><em/></span>; if(object.type==='well')return <span className="well landmark" style={style}>✦</span>; if(object.type==='berryBush')return <span className="bush landmark" style={style}>●<small>{object.stock}</small></span>; if(object.type==='bench')return <span className="bench" style={style}/>; if(object.type==='table')return <span className="table" style={style}/>; return null; }
function NeedBar({label,value}:{label:string;value:number}) { return <div className="need"><span>{label}</span><div><i style={{width:`${value}%`}}/></div><b>{Math.round(value)}</b></div> }
function Inspector({ agent, world, close }:{agent:Agent;world:SimulationWorld;close:()=>void}) { const lookup=(id:string)=>world.agents.find(a=>a.id===id); return <aside className="inspector"><button className="close" onClick={close}>×</button><div className="profile"><span className="portrait" style={{background:agent.shirt}}><i style={{background:agent.color}}/></span><div><h2>{agent.name}</h2><p>{agent.age} years · {agent.traits.join(' · ')}</p></div></div><section><label>NOW</label><strong>{agent.currentAction.kind === 'WalkTo' ? 'Walking with purpose' : agent.currentAction.kind}</strong><p className="goal">Goal: {agent.currentGoal}</p></section><section><label>WELLBEING</label>{needs.map(n=><NeedBar key={n} label={n} value={agent.needs[n]}/>)}</section><section><label>RECENTLY</label>{agent.recentMemories.slice(0,3).map(m=><p className="memory" key={m.id}>{m.description}</p>)}</section><section><label>CONNECTIONS</label>{agent.relationships.map(r=><p className="relation" key={r.agentId}><b>{lookup(r.agentId)?.name}</b><span>{r.label} · {Math.round(r.affinity*100)}%</span></p>)}</section><section><label>POCKETS</label><p>{agent.inventory.length?agent.inventory.join(', '):'Nothing carried'}</p></section></aside> }
export function App() {
  const [world,setWorld]=useState(createWorld); const [speed,setSpeed]=useState(1); const [selected,setSelected]=useState<string>('a-mara'); const [debug,setDebug]=useState(false); const [zoom,setZoom]=useState(1);
  useEffect(()=>{if(!speed)return; const id=setInterval(()=>setWorld(tickWorld),Math.max(90,700/speed)); return()=>clearInterval(id);},[speed]);
  const agent=world.agents.find(a=>a.id===selected); const sky=useMemo(()=>{const h=world.minute/60;return h<7||h>20?'night':h<9?'dawn':'day';},[world.minute]);
  return <main className={`app ${sky}`}><header><div className="brand"><span>✽</span><div><h1>Willowmere</h1><p>an autonomous little world</p></div></div><div className="time"><b>{formatTime(world)}</b><span>{sky === 'night' ? 'Moonlit quiet' : sky === 'dawn' ? 'Morning mist' : 'Golden meadow'}</span></div><div className="controls"><button className={speed===0?'active':''} onClick={()=>setSpeed(0)}>Ⅱ</button><button className={speed===1?'active':''} onClick={()=>setSpeed(1)}>1×</button><button className={speed===3?'active':''} onClick={()=>setSpeed(3)}>3×</button><button onClick={()=>setZoom(z=>z===1?1.14:1)}>{zoom===1?'＋':'−'}</button><button className={debug?'active':''} onClick={()=>setDebug(!debug)}>⌘</button></div></header><div className="viewport"><div className="world" style={{transform:`scale(${zoom})`}}><div className="river"/><div className="path path-one"/><div className="path path-two"/><div className="garden"><i/><i/><i/><i/></div>{world.objects.filter(o=>o.type!=='bed').map(o=><ObjectView object={o} key={o.id}/>)}<span className="pond"><i/></span>{world.agents.map(a=><Person agent={a} key={a.id} selected={a.id===selected} onSelect={()=>setSelected(a.id)}/>)}</div><div className="legend"><span><i className="dot"/> autonomous residents</span><span>Click a resident to observe</span></div>{debug&&<div className="debug"><b>DEVELOPER VIEW</b><p>tick {world.tick} · seed {world.seed}</p><p>World truth → perception → cognition → validated action → memory</p><p>{world.events.length} events in history · berry stock {world.objects.find(o=>o.id==='berries')?.stock}</p></div>}</div><div className="bottom"><div><b>Settlement pulse</b><span>{world.agents.filter(a=>a.currentAction.kind==='WalkTo').length} residents en route · actions validate at their targets</span></div><div className="event"><b>Latest</b><span>{world.events[0]?.description ?? 'The residents are beginning their day.'}</span></div></div>{agent&&<Inspector agent={agent} world={world} close={()=>setSelected('')}/>}</main>;
}
