import OpenAI from 'openai';
import { DecisionSchema, type DecisionResponse, type MindContext, type ProviderStatus } from '../src/cognition/contracts';
const base=(process.env.OLLAMA_BASE_URL??'http://127.0.0.1:11434').replace(/\/$/,'');
const timeout=Number(process.env.OLLAMA_REQUEST_TIMEOUT_MS??60000);
const schema={type:'object',properties:{goal:{type:'string'},action:{type:'string',enum:['Drink','Eat','Sleep','TalkTo','Observe']},targetId:{type:'string'},intent:{type:'string'},utterance:{type:'string'}},required:['goal','action','targetId','intent'],additionalProperties:false};
const prompt=(context:MindContext)=>`You are ${context.identity.name}, a human resident of Willowmere. Act naturally from only the supplied knowledge. Never invent facts, claim success, mention AI/simulation, or choose an action/target not offered. Return JSON only. intent is one short public sentence, never hidden reasoning.\n${JSON.stringify(context)}`;
export async function ollamaModels(){const response=await fetch(`${base}/api/tags`,{signal:AbortSignal.timeout(3000)});if(!response.ok)throw new Error(`Ollama tags: ${response.status}`);const json=await response.json() as {models?:{name:string;details?:{parameter_size?:string;quantization_level?:string};size?:number}[]};return(json.models??[]).map(m=>({name:m.name,size:m.details?.parameter_size??m.size,quantization:m.details?.quantization_level}));}
export async function providerStatus():Promise<ProviderStatus[]>{let ollama:ProviderStatus={id:'ollama',available:false,label:'Ollama',detail:'OFFLINE'};try{const models=await ollamaModels();ollama={id:'ollama',available:true,label:'Ollama',detail:`${models.length} model${models.length===1?'':'s'}`};}catch{ollama.detail='OFFLINE';}return[{id:'local-rules',available:true,label:'Local Rules'},ollama,{id:'openai',available:!!process.env.OPENAI_API_KEY,label:'OpenAI',detail:process.env.OPENAI_API_KEY?'Configured':'API key not configured'}];}
export async function ollamaDecision(context:MindContext,model:string):Promise<DecisionResponse>{const body={model,prompt:prompt(context),stream:false,format:schema,options:{temperature:.35,num_ctx:Number(process.env.OLLAMA_NUM_CTX??8192)},keep_alive:process.env.OLLAMA_KEEP_ALIVE??'15m',think:(process.env.OLLAMA_THINK??'false')==='true'};const response=await fetch(`${base}/api/generate`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(timeout)});if(!response.ok)throw new Error(`Ollama generate: ${response.status}`);const json=await response.json() as {response?:string};return DecisionSchema.parse(JSON.parse(json.response??''));}
export async function openAiDecision(context:MindContext,model:string):Promise<DecisionResponse>{if(!process.env.OPENAI_API_KEY)throw new Error('OpenAI is not configured');const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const response=await client.responses.create({model:model||process.env.OPENAI_MODEL||'gpt-4.1-mini',input:prompt(context),text:{format:{type:'json_schema',name:'willowmere_decision',strict:true,schema}}});return DecisionSchema.parse(JSON.parse(response.output_text));}
