import { Canvas, useFrame } from '@react-three/fiber';
import { Line, OrbitControls, Sky } from '@react-three/drei';
import { useMemo, useRef } from 'react';
import * as THREE from 'three';
import type { Agent, SimulationWorld, WorldObject } from '../domain/types';
import { toWorld } from './coordinates';

type SceneProps={world:SimulationWorld;selectedId:string;onSelect:(id:string)=>void;debug:boolean};
const seeded=(n:number)=>{const x=Math.sin(n*923.17)*43758.5453;return x-Math.floor(x)};
function Terrain(){const grass=useMemo(()=>Array.from({length:150},(_,i)=>{const x=seeded(i)*25-12.5,z=seeded(i+50)*25-12.5;return{x,z,s:.03+seeded(i+90)*.045,r:seeded(i+120)*Math.PI};}),[]);return <group><mesh rotation={[-Math.PI/2,0,0]} receiveShadow><planeGeometry args={[28,28,1,1]}/><meshStandardMaterial color="#567c43" roughness={1}/></mesh>{grass.map((g,i)=><mesh key={i} position={[g.x,g.s/2,g.z]} rotation={[0,g.r,0]}><coneGeometry args={[g.s*.55,g.s,3]}/><meshStandardMaterial color={i%5===0?'#89a853':'#6f994e'} roughness={1}/></mesh>)}<mesh position={[4.15,.028,0]} rotation={[-Math.PI/2,0,0]} receiveShadow><planeGeometry args={[2.8,28]}/><meshStandardMaterial color="#477f95" roughness={.25} metalness={.15}/></mesh><Path/><Bridge/></group>}
function Path(){return <group>{[[[-8,0,-2],[-3,0,-1],[1,0,.2],[5,0,.2]],[[0,0,5],[-1,0,1],[-3,0,-4]]].map((points,i)=><Line key={i} points={points as [number,number,number][]} color="#a98e63" lineWidth={8}/>)}</group>}
function Bridge(){return <group position={[4.15,.32,.25]}><mesh castShadow><boxGeometry args={[3.1,.24,1.05]}/><meshStandardMaterial color="#7a4931" roughness={.8}/></mesh>{[-1.35,-.45,.45,1.35].map(x=><mesh key={x} position={[x,.18,0]} castShadow><boxGeometry args={[(.08),.22,1.18]}/><meshStandardMaterial color="#bd8153"/></mesh>)}</group>}
function Cabin({object,index}:{object:WorldObject;index:number}){const[x,,z]=toWorld(object.position);const wall=['#a36b4d','#8f6546','#9c7651'][index]??'#9c7651';return <group position={[x,.45,z]} rotation={[0,index*.14,0]}><mesh castShadow receiveShadow><boxGeometry args={[2.9,1.4,2.25]}/><meshStandardMaterial color={wall} roughness={.9}/></mesh><mesh position={[0,1.12,0]} castShadow rotation={[0,Math.PI/4,0]}><coneGeometry args={[2.25,1.45,4]}/><meshStandardMaterial color={index===1?'#4c5a49':'#5c4033'} roughness={.9}/></mesh><mesh position={[0,.1,1.14]}><boxGeometry args={[.52,.85,.05]}/><meshStandardMaterial color="#3c3028"/></mesh>{[-.75,.75].map(x=><mesh key={x} position={[x,.62,1.16]}><boxGeometry args={[.38,.34,.04]}/><meshStandardMaterial emissive="#e7bc65" emissiveIntensity={.25} color="#e5d1a1"/></mesh>)}</group>}
function Tree({object,index}:{object:WorldObject;index:number}){const[x,,z]=toWorld(object.position),s=.75+seeded(index)*.55;return <group position={[x,0,z]} rotation={[0,seeded(index+20)*6,0]} scale={s}><mesh position={[0,.65,0]} castShadow><cylinderGeometry args={[.13,.18,1.3,7]}/><meshStandardMaterial color="#5a4230"/></mesh><mesh position={[0,1.55,0]} castShadow><dodecahedronGeometry args={[.7,0]}/><meshStandardMaterial color={index%3===0?'#3e7041':'#4f8149'} roughness={1}/></mesh><mesh position={[.35,1.85,.05]} castShadow><dodecahedronGeometry args={[.5,0]}/><meshStandardMaterial color="#588a4d" roughness={1}/></mesh></group>}
function Well({object}:{object:WorldObject}){const[x,,z]=toWorld(object.position);return <group position={[x,.25,z]}><mesh castShadow><cylinderGeometry args={[.52,.58,.45,14]}/><meshStandardMaterial color="#7e8077" roughness={1}/></mesh><mesh position={[0,.24,0]}><cylinderGeometry args={[.34,.34,.02,14]}/><meshStandardMaterial color="#294d59" roughness={.2}/></mesh><mesh position={[0,.72,0]} rotation={[0,0,Math.PI/2]}><cylinderGeometry args={[.04,.04,1.35,8]}/><meshStandardMaterial color="#5e4030"/></mesh></group>}
function Berries({object}:{object:WorldObject}){const[x,,z]=toWorld(object.position);return <group position={[x,.24,z]}>{Array.from({length:7},(_,i)=><mesh key={i} position={[(seeded(i)*.8)-.4,seeded(i+7)*.35,(seeded(i+13)*.8)-.4]} castShadow><sphereGeometry args={[.24,7,7]}/><meshStandardMaterial color={i%2?'#3d6b3b':'#4d7c41'}/></mesh>)}{[0,1,2].map(i=><mesh key={`b${i}`} position={[i*.18-.18,.28,.2]}><sphereGeometry args={[.06,6,6]}/><meshStandardMaterial color="#a84e4f"/></mesh>)}</group>}
function Props({objects}:{objects:WorldObject[]}){return <>{objects.filter(o=>o.type==='cabin').map((o,i)=><Cabin key={o.id} object={o} index={i}/>)}{objects.filter(o=>o.type==='tree').map((o,i)=><Tree key={o.id} object={o} index={i}/>)}{objects.filter(o=>o.type==='well').map(o=><Well key={o.id} object={o}/>)}{objects.filter(o=>o.type==='berryBush').map(o=><Berries key={o.id} object={o}/>)}{objects.filter(o=>o.type==='bench'||o.type==='table').map(o=>{const[x,,z]=toWorld(o.position);return <mesh key={o.id} position={[x,.26,z]} castShadow><boxGeometry args={o.type==='table'?[1.1,.16,.65]:[1.15,.16,.3]}/><meshStandardMaterial color="#744c34"/></mesh>})}</>}
function Resident({agent,selected,onSelect}:{agent:Agent;selected:boolean;onSelect:()=>void}){const ref=useRef<THREE.Group>(null);const target=toWorld(agent.position);useFrame(({clock},delta)=>{if(!ref.current)return;ref.current.position.x=THREE.MathUtils.damp(ref.current.position.x,target[0],7,delta);ref.current.position.z=THREE.MathUtils.damp(ref.current.position.z,target[2],7,delta);ref.current.rotation.y=THREE.MathUtils.damp(ref.current.rotation.y,agent.facing==='left'?Math.PI:0,8,delta);const walking=agent.currentAction.kind==='WalkTo';ref.current.position.y=walking?Math.abs(Math.sin(clock.elapsedTime*9))*.07:0;});return <group ref={ref} position={target} onClick={e=>{e.stopPropagation();onSelect()}}><mesh position={[0,.95,0]} castShadow><sphereGeometry args={[.23,12,12]}/><meshStandardMaterial color="#e5b18c"/></mesh><mesh position={[0,.57,0]} castShadow><capsuleGeometry args={[.22,.48,5,8]}/><meshStandardMaterial color={agent.shirt}/></mesh><mesh position={[-.28,.58,0]} rotation={[0,0,.15]} castShadow><capsuleGeometry args={[.055,.36,4,6]}/><meshStandardMaterial color="#e5b18c"/></mesh><mesh position={[.28,.58,0]} rotation={[0,0,-.15]} castShadow><capsuleGeometry args={[.055,.36,4,6]}/><meshStandardMaterial color="#e5b18c"/></mesh>{[-.11,.11].map(x=><mesh key={x} position={[x,.18,0]} castShadow><capsuleGeometry args={[.075,.38,4,6]}/><meshStandardMaterial color="#3e4850"/></mesh>)}<mesh position={[0,1.12,-.03]} castShadow><sphereGeometry args={[.25,10,10,0,Math.PI*2,0,Math.PI/2]}/><meshStandardMaterial color={agent.color}/></mesh>{selected&&<mesh rotation={[-Math.PI/2,0,0]} position={[0,.015,0]}><ringGeometry args={[.45,.58,24]}/><meshBasicMaterial color="#ffe58a" transparent opacity={.9}/></mesh>}</group>}
function Debug({agent}:{agent:Agent}){const points=(agent.currentAction.path??[]).map(toWorld);const[x,,z]=toWorld(agent.position);return <>{points.length>1&&<Line points={[[x,.08,z],...points.map(([a,,b])=>[a,.08,b])] as [number,number,number][]} color="#ffe68a" lineWidth={2}/>}<mesh position={[x,.02,z]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[agent.perception.radius/4-.02,agent.perception.radius/4,48]}/><meshBasicMaterial color="#f6dc86" transparent opacity={.45}/></mesh></>}
function Lighting({minute}:{minute:number}){const hour=minute/60;const night=hour<6||hour>20;const sunset=hour<8||hour>17;const color=night?'#182841':sunset?'#ffb36e':'#e5f3cf';return <><color attach="background" args={[night?'#101928':sunset?'#d99565':'#8eb6d0']}/><fog attach="fog" args={[night?'#101928':'#8eb6d0',16,42]}/><ambientLight intensity={night?.32:.72} color={color}/><directionalLight position={[8,14,6]} intensity={night?.35:sunset?1.25:1.7} color={color} castShadow shadow-mapSize={[1024,1024]}/><Sky distance={450000} sunPosition={[5,1,4]} turbidity={night?1:7} rayleigh={night?.3:2}/></>}
function Scene({world,selectedId,onSelect,debug}:SceneProps){const selected=world.agents.find(a=>a.id===selectedId);return <><Lighting minute={world.minute}/><Terrain/><Props objects={world.objects}/>{world.agents.map(a=><Resident key={a.id} agent={a} selected={a.id===selectedId} onSelect={()=>onSelect(a.id)}/>)}{debug&&selected&&<Debug agent={selected}/>}<OrbitControls makeDefault enablePan enableRotate minDistance={11} maxDistance={31} maxPolarAngle={Math.PI/2.25} minPolarAngle={Math.PI/5}/></>}
export function WillowmereCanvas(props:SceneProps){return <Canvas shadows camera={{position:[14,17,18],fov:42}} dpr={[1,1.5]}><Scene {...props}/></Canvas>}
